### PR TITLE
Dark Mode for common icons

### PR DESCRIPTION
**Pull request by stychos**
Converted few (mostly used) icons for the Dark Mode.

### CODE REVIEW

**Comment by stychos** [comment]
Can someone check it on retina displays? I have some fears about @3x parts.

**Comment by Kaspik** [comment]
Verified on iMac 5K, looks great, thank you!

**Comment by stychos** [comment]
You're welcome, thanks for the merge!

**Comment by andyvenus** [comment]
It seems the dark-mode icons are being used even when not using dark mode?

screenshot 2019-02-20 at 14 03 57

**Comment by stychos** [comment]
Hm.. I could swear I saw how they change. Going to check how to fix that.

**Comment by dmoagx** [comment]
I'll have to revert this for two reasons:
* Use of xcassets violates the current Xcode compatibility goal
* Maintaining 4 or more variants of a single icon is not sustainable. We have decided to use vector template icons instead. See the section "Use Template Images" in https://developer.apple.com/documentation/appkit/images_and_pdf/providing_images_for_different_appearances?language=objc

Note there is no need for an xcassets file. The template icon simply needs to be named `somethingTemplate.pdf` for the OS to correctly handle it.

**Comment by Kaspik** [comment]
... so many comptibility issues. 🤦‍♂️ I’m really looking forward for 1.2.0 release of we are then going to drop suppourt for 10.6-10.9... sorry @dmoagx

**Comment by dmoagx** [comment]
bildschirmfoto 2019-02-20 um 23 33 48 713
Indeed

**Comment by stychos** [comment]
Sorry guys, this PR really terrible.

**Comment by stychos** [comment]
> Maintaining 4 or more variants of a single icon is not sustainable (both for maintenance and size of the application)
Tried to make few pdf icons in Illustrator and their pdf file have a minimum size ~10k, while four png icons average size is ~3k, so it's definitely not about size.

What about using of NS*Template icons?

**Comment by stychos** [comment]
I prepared changes for Template icons: https://github.com/stychos/sequelpro/commits/dark-icons, it looks proper now in both modes:
Screenshot 2019-03-16 at 06 21 18 copy
Should I open a new PR or maybe reopen this?

**Pull request merged**
