### PR TITLE
Dark icons templates

### PR DESCRIPTION
**Pull request by stychos**
Here's reworked icons for the dark mode.
There's maybe some additional work needed for the refresh, select*, edit_mode* and filter* icons (I am bad artist), but now this works for both dark and white modes.

Screenshot 2019-03-18 at 20 34 27 copy

Source file: [icons.ai.zip](https://github.com/sequelpro/sequelpro/files/2979680/icons.ai.zip)

### CODE REVIEW

**Comment by stychos** [comment]
Oh hell, just seen a policy about xib files. Will update this later.

**Comment by stychos** [comment]
Done.

**Comment by ghs** [comment]
On Nightly build 5438 icons for previous and next pages does not have a state and is not clearly visible if they are active or not

**Comment by stychos** [comment]
@ghs this branch isn't merged, so it absent in nightly builds

**Pull request closed without merging**
