### PR TITLE
Skip localisations processing for nightly builds

### PR DESCRIPTION
**Pull request by Kaspik**
- Update readme
- Disable localisations processing for nightly builds

### CODE REVIEW

**Comment by stuconnolly** [comment]
So this is @rowanbeentje's nightly build script that we used to use when I hosted a buildbot instance, but it's no longer used.

I'd love to get the nightly's back up and running, but afraid I'm in the same boat as @dmoagx and I don't have access to the server. Rowan has offered the use of his build machine again and I've got server space to host anything, but we would be deviating from the project.

**Comment by Kaspik** [comment]
@stuconnolly Mmmm, okay. So we really just need to try to get answers / access to another parts of the project from Abhi, ideally on Slack.

**Comment by rowanbeentje** [comment]
The other bit that we're currently missing is the signing keys, iirc.  I do still have access to the Apple Developer Account for Sequel Pro, but that doesn't give access to existing private keys.  Potentially @mattlangtree can help with this bit as it looks like they generated the existing ones (that would also be needed for a final release build!).

**Comment by Kaspik** [comment]
Another option would be to create new one in Developer Portal, but let's try to get existing ones first.

**Comment by anotherdevs** [comment]
May I redirect your attention to https://github.com/sequelpro/sequelpro/issues/3184#issuecomment-425106240 @Kaspik. As I told you: this project cannot continue before @abhibeckert and @mattlangtree give up control over this project. Right now they sit on the certificates and you are unable to get the build server up and running.

**Comment by toddstoffel** [comment]
@anotherdevs et al. I don't think hostility or threats is the best approach here. I would recommend against forking this project as it will almost certainly not succeed. I for one am fully supportive of Abhi and company continuing their work.  They have been working on this project for more than 10 years. Just relax.

**Comment by anotherdevs** [comment]
@toddstoffel To insinuate that I am threatening someone is just plain stupid. I am stating facts based on the founders behaviour, what @dmoagx have expressed (https://github.com/sequelpro/sequelpro/issues/3034#issuecomment-424656667) and the current state this project is in. They founders continues to tell us that they will fix the problems, and they promised they would talk it over this weekend. @Kaspik insured us (https://github.com/sequelpro/sequelpro/issues/3184#issuecomment-425104254) that we would see progess this Monday. ;-) I for one does not care who runs the project, however they current founders (and owners) are not acting professionel enough to run this large project. I am not sure why @dmoagx continues to commit to this dead project, but I salute him. However I do not think he should continue, because no one shows him the respect that he deserves;
dmoagx: 569 commits: 234,699 ++  263,789 --

**Comment by anotherdevs** [comment]
@toddstoffel Let me just be clear, I do not have anything against the founders, however no one is getting anywhere.

They are not contributing to the project (due to personal reasons). Since they are not:

1) handing over ownership
2) not contributing

we are stuck and cannot release a new version with all the bug fixes from @dmoagx.

They need to react. Either they are in or out. All evidence shows that they are out.

I would love to see you do something without their help. But you can’t. No one can. That is why a fork is the last option. To which it right now looks like is the ONLY option.

**Comment by zorak997** [comment]
@anotherdevs your comments on here are RUDE. If you don’t like the product, use another one. Don’t try to bully the founder. You obviously threatened to fork it despite your denial above.

**Pull request closed without merging**
