### PR TITLE
Feature/2156

### PR DESCRIPTION
**Pull request by nacho4d**
#2156 Done sir!
:)

### CODE REVIEW

**Comment by dmoagx** [comment]
We still seem to be missing something.
Normally the items in the Substitution and Spelling menu should have checkmarks when enabled, but that doesn't seem to work.

**Comment by dmoagx** [comment]
Ah well, obvious...we don't call super in `[SPTextView validateMenuItem:]`

**Comment by nacho4d** [comment]
You are right, I guess most SP users use keyboard shortcuts so nobody looks at the edit menu. I will fix it.

**Comment by nacho4d** [comment]
@dmoagx One question: Is this line correct? It looks kind of odd to me
https://github.com/sequelpro/sequelpro/blob/master/Source/SPTextView.m#L3217

If you want to return YES for words between 1 and 64 characters it should be
`return (stringSize && stringSize < 65);` 
or if you want to return YES for words longer than 64
`return (stringSize > 64);`

What is the specification for this? Since it is a very small thing I thought it could be solved in the same branch.

**Comment by dmoagx** [comment]
The truthiness table should look like
```
A  | (A || A > 64) =
0  |  F      F     F
1  |  T   skipped  T
65 |  T   skipped  T 
```
which doesn't make much sense IMHO.

The comment 
```
// Enable or disable the search in the MySQL help menu item depending on whether there is a 
// selection and whether it is a reasonable length.
```
suggests that 1 ≤ stringSize ≤ 64 was intended, though. :)

**Comment by nacho4d** [comment]
@dmoagx  I've updated the pull request :)

**Pull request merged**
