### PR TITLE
#3434 Interprete data as pretty JSON

### PR DESCRIPTION
**Pull request by e3duardo**
Hello, like I say in issue #3434, I would like to code an interpreter for JSON. I never wrote a line on xcode, but i managed how to implement this.

Please, review and merge if possible! I dont know how to generate a binary, to my own use, that doesn`t ask password all time .

image

### CODE REVIEW

**Comment by stychos** [comment]
As I seen from @dmoagx messages before, you must review your FieldEditorSheet.xib file to reflect only changed properties. It's because if you just open it in Xcode change single line anywhere and save, it will change a lot of properties which is hard to track.

**Comment by e3duardo** [comment]
> As I seen from @dmoagx messages before, you must review your FieldEditorSheet.xib file to reflect only changed properties. It's because if you just open it in Xcode change single line anywhere and save, it will change a lot of properties which is hard to track.

I`ll try that. In fact, I see that's too many lines changed, but I`ve supposed it is normal

**Comment by e3duardo** [comment]
@stychos I checked the file on commit [ce47e1c](https://github.com/sequelpro/sequelpro/pull/3446/commits/ce47e1cc3c110c521e83da498a534417df8269b4). Was that what you said?

**Comment by stychos** [comment]
Look at these three pairs of lines:
Screenshot 2019-04-11 at 00 35 19
if you're not changed them with a purpose then revert them back. If it's your action, then ok.
Anyway, I am not a bigger coder in macOS than you, so my opinions are not mandatory here.

**Comment by e3duardo** [comment]
> Look at these three pairs of lines:
> Screenshot 2019-04-11 at 00 35 19
> if you're not changed them with a purpose then revert them back. If it's your action, then ok.
> Anyway, I am not a bigger coder in macOS than you, so my opinions are not mandatory here.

In the image are just my changes. What I tried to say is that I had done a checkout on the file and just rewritten what I actually modified.

Thanks for the support. I hope this is able to one of the nightly build soon.

**Comment by stychos** [comment]
Hope too, this request is highly useful for me. Btw, when you build your own binary, just press "always allow" when you connecting and it will never ask for password again. Usable until you have hundreds of hosts.

**Comment by stychos** [comment]
Propose you to backport https://github.com/stychos/sequelpro/commit/370102a822a1d156a05118a3de43d754e50a3681, will set the same font in `jsonTextView` as in origin `editTextView`.

**Comment by e3duardo** [comment]
I'm closing this, since I no longer use Sequel

**Pull request closed without merging**
