### PR TITLE
[RFC] SPMySQLFramework: upgrade libmysqlclient.a for TLSv1.1 support

### LINKED ISSUE #3492: Upgrade libmysqlclient.a for TLSv1.1 support (for MariaDB 10.4 default installs)
Sequel Pro currently appears to ship a `libmysqlclient.a` library from the 5.5.x series.  This libary only supports the older and (security wise) broken TLSv1.0 protocol.

- https://github.com/sequelpro/sequelpro/commits/master/Frameworks/SPMySQLFramework/MySQL%20Client%20Libraries

The most recent GA release of MariaDB, version 10.4.6, replaces the embedded yaSSL library (not maintained) with wolfSSL (maintained, supports modern TLS) and ships with a newly introduced `tls_version` setting that defaults to `TLSv1.1,TLSv1.2,TLSv1.3`.  References:

- https://mariadb.com/kb/en/library/secure-connections-overview/#enabling-specific-tls-protocol-versions
- https://mariadb.com/kb/en/library/ssltls-system-variables/#tls_version
- https://jira.mariadb.org/browse/MDEV-19542 (Disable SSLv3 and TLSv1.0)
- https://jira.mariadb.org/browse/MDEV-18531 (Use WolfSSL instead of YaSSL as "bundled" SSL)

A `libmysqlclient.a` library from the 5.7.x series appears to support both TLSv1.0 and TLSv1.1:

- https://bugs.mysql.com/bug.php?id=75239

Would it be possible to upgrade the MySQL client library to a newer release to make it support a slightly more modern version of TLS?  That would allow Sequel Pro to connect to MariaDB 10.4 servers out of the box and also improve security.

### PR DESCRIPTION
**Pull request by noahwilliamsson**
MariaDB 10.4.6 (GA as of June, 2019) replaces the yaSSL embedded TLS library
with wolfSSL and drops support for TLS 1.0 in its default configuration
(`tls_version=TLSv1.1,TLSv1.2,TLSv1.3`).

Before MySQL 5.7, the embedded yaSSL library used by libmysqlclient.a only
supported TLS 1.0.

This changeset upgrades the MySQL client library to 5.7 to allow Sequel Pro
to connect to TLS protected MariaDB 10.4 servers.

- upgrade libmysqlclient.a and includes from 5.5.56 to 5.7.26
- drop custom mysql patches (all types are present in MySQL 5.6 and 5.7)
- add `-lc++` to SPMySQLFramework linker flags
- add `-b <boost source path>` option to mysqlclient build script

Fixes #3492.

NOTE: When testing this I was using `MIN_OS_X_VERSION=10.13` in `Frameworks/SPMySQLFramework/build-mysql-client.sh` and built everything with Xcode 9.2 on macOS Sierra.

### CODE REVIEW

**Comment by Kaspik** [comment]
One more Q: `When testing this I was using MIN_OS_X_VERSION=10.13 in Frameworks/SPMySQLFramework/build-mysql-client.sh and built everything with Xcode 9.2 on macOS Sierra.` - did you add this check / verification to this PR somewhere / somehow / documented that too?

**Comment by noahwilliamsson** [comment]
@Kaspik If you're asking whether I raised the minimum required build version to 10.13, then no.  10.13 was the oldest MacOS version I had access to, so I just wanted to be clear that that was what I was testing with.  I didn't include the local changes I did in order to build with 10.13 instead of 10.6 (or whatever the default in the project is) in this MR.

**Comment by Kaspik** [comment]
Would you mind checking https://github.com/sequelpro/sequelpro/issues/3705 and then probably doing the same (if necessary) there from `dev`?

**Comment by noahwilliamsson** [comment]
@Kaspik Sorry, it's been too long.  I'm unfortunately no longer working with TLS protected MariaDB servers and don't have access to older macOS installations.

If you have access to TLS protected MariaDB servers, perhaps you can cherry-pick these changes and either test them locally or try one of the forks where they went in (see pingbacks in #3492).

**Comment by Kaspik** [comment]
Already merged to Sequel Ace.

**Pull request closed without merging**
